import Navbar from "@/components/organisms/Navbar";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "next-themes";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Go Cloud",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html
            lang="en"
            className="dark"
            style={{
                colorScheme: "dark",
            }}
        >
            <body
                className={cn(
                    "flex h-screen w-screen flex-col",
                    inter.className
                )}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <Providers>
                        <Navbar />
                        <main className="relative mx-auto flex h-navScreen w-full flex-grow overflow-hidden magicpattern">
                            <div className="flex h-full w-full backdrop-blur-sm">
                                {children}
                            </div>
                        </main>
                    </Providers>
                </ThemeProvider>
            </body>
        </html >
    );
}
